import type { JobListItem } from "../types/job"

export const jobListFixtures: JobListItem[] = [
  {
    id: "a63f1ca8292ecdd80c30",
    companyId: "4c6a2dc35bec6d932b68",
    companyName: "CJ ENM",
    title: "Data Scientist 채용",
    jobName: "Data Scientist",
    category: "개발·데이터",
    employmentType: "정규직",
    location: "서울",
    deadline: "2026-07-03",
    status: "open",
    tags: ["Python", "SQL", "LLM"],
  },
  {
    id: "b07667cb3eb79ffd3139",
    companyId: "4c6a2dc35bec6d932b68",
    companyName: "CJ ENM",
    title: "Mnet Plus Product Designer 경력채용",
    jobName: "Product Designer",
    category: "디자인",
    employmentType: "정규직",
    location: "서울",
    deadline: "2026-06-26",
    status: "open",
    tags: ["UI/UX", "디자인 시스템", "프로토타이핑"],
  },
  {
    id: "62945315cd3b3c07da52",
    companyId: "4c6a2dc35bec6d932b68",
    companyName: "CJ ENM",
    title: "[Mnet Plus] Web/App Lead 경력채용",
    jobName: "Web/App Lead",
    category: "개발·데이터",
    employmentType: "정규직 (협의)",
    location: "서울 마포구",
    deadline: null,
    status: "rolling",
    tags: ["React Native", "TypeScript", "Tech Lead"],
  },
  {
    id: "4337b91b45eba194235b",
    companyId: "4c6a2dc35bec6d932b68",
    companyName: "CJ ENM",
    title: "커머스부문 추천 플랫폼 엔지니어",
    jobName: "추천 플랫폼 엔지니어",
    category: "개발·데이터",
    employmentType: "정규직",
    location: "서울",
    deadline: "2026-06-21",
    status: "closed",
    tags: ["Java", "Python", "AWS"],
  },
  {
    id: "3c3fa750ba51bce320ea",
    companyId: "4c6a2dc35bec6d932b68",
    companyName: "CJ ENM",
    title: "커머스부문 개인정보보호 담당자",
    jobName: "개인정보보호 담당자",
    category: "보안",
    employmentType: "정규직",
    location: "서울",
    deadline: "2026-06-14",
    status: "closed",
    tags: ["개인정보보호", "ISMS-P", "Cloud"],
  },
]
