import type { JobPostingFixture } from "../types/search"

export const cjEnmJobFixtures: JobPostingFixture[] = [
  {
    id: "e3b1bca75a26a4582ed16ec4",
    companyName: "(주)CJ ENM",
    title: "CJ ENM 커머스부문 [추천 플랫폼 엔지니어] 경력사원 채용",
    job: {
      name: "추천 플랫폼 엔지니어",
      headcount: "00명",
      locations: ["서울"],
      responsibilities: [
        "추천 모델 서비스화 및 Java/Python 기반 백엔드 시스템 개발",
        "추천 모델과 추천 로직을 서비스 환경에 연결하는 백엔드 아키텍처 설계 및 개발",
        "대용량 트래픽 환경의 추천 서빙 API 설계 및 레이턴시 최적화",
        "Airflow 기반 데이터 배치 프로세스 운영 및 관리",
        "실시간 사용자 행동 데이터 수집 파이프라인 구축 및 운영",
        "AWS 컨테이너 환경의 추천 서비스 인프라 운영 및 최적화",
      ],
      requirements: [
        "Java/Spring 기반 서비스 개발 및 운영 경력",
        "대규모 데이터 파이프라인 개발 및 운영 경험",
        "대용량 API 시스템 성능 최적화 경험",
        "Airflow 기반 Python 데이터 배치 운영 경험",
        "AWS, Docker, ECS 등 클라우드 인프라 이해",
      ],
      preferred: [
        "AWS Athena, Glue 등 빅데이터 쿼리 엔진 활용 경험",
        "Kafka, Kinesis 등 실시간 스트리밍 처리 경험",
        "추천 모델 서빙 및 MLOps 경험",
        "이커머스 추천 플랫폼 경험",
      ],
    },
    qualification: {
      education: "",
      major: "",
      documents: [],
    },
    process: ["서류 접수: 2026.06.10 ~ 2026.06.21"],
    workConditions: {
      employmentType: "정규직",
      workType: "",
      salary: "",
      benefits: [],
      deadline: "2026-06-21",
      deadlineType: "fixed_date",
    },
  },
  {
    id: "5e9cabd040c307d7aa142e73",
    companyName: "CJ ENM",
    title: "Data Scientist 채용",
    job: {
      name: "Data Scientist",
      headcount: "00명",
      locations: ["서울"],
      responsibilities: [
        "Python 및 SQL을 활용한 콘텐츠 Value Chain 데이터 분석",
        "시청 지표와 사용자 반응 데이터 기반 콘텐츠 성과 분석",
        "비즈니스 핵심 문제 정의 및 데이터 기반 의사결정 지원",
        "분석용 데이터셋과 데이터 마트 설계 협업",
        "BI 도구를 활용한 사내 대시보드 구축 및 운영",
        "LLM 기반 AI Agent와 자연어 데이터 조회 구조 설계",
        "Databricks 환경의 대용량 데이터 탐색 및 모델링",
      ],
      requirements: [
        "데이터 분석 또는 데이터 사이언스 관련 경력 3년 이상",
        "Python 기반 데이터 처리 및 분석 역량",
        "SQL 활용 데이터 추출 및 가공 능력",
        "비정형 데이터 처리 및 활용 경험",
        "LLM, RAG, 벡터DB 또는 임베딩 검색 구조 이해",
      ],
      preferred: [
        "엔터테인먼트 산업 데이터 분석 경험",
        "LLM 기반 서비스 또는 AI Agent 개발 경험",
        "Databricks 또는 Spark 기반 분석 경험",
        "데이터 분석 관련 자격증 또는 프로젝트 경험",
      ],
    },
    qualification: {
      education: "4년제 대학 졸업자 이상",
      major: "통계학, 컴퓨터공학, 산업공학, 수학 등 관련 전공",
      documents: ["포트폴리오 제출 필수"],
    },
    process: [
      "서류전형",
      "1차 면접",
      "2차 면접",
      "평판조회",
      "채용검진",
      "처우협의",
      "합격자 발표",
    ],
    workConditions: {
      employmentType: "정규직",
      workType: "",
      salary: "",
      benefits: ["입사일로부터 3개월 수습기간 적용"],
      deadline: "2026-07-03",
      deadlineType: "fixed_date",
    },
  },
  {
    id: "6d5b7abda7cc9dab87f8b17c",
    companyName: "CJ ENM",
    title: "Mnet Plus Product Designer 경력채용",
    job: {
      name: "Product Designer",
      headcount: "00명",
      locations: ["서울"],
      responsibilities: [
        "Mnet Plus 사용자 중심 제품 및 서비스 설계",
        "사용자 조사와 테스트를 통한 고객 니즈 파악",
        "정량·정성 데이터 분석 및 개선 기회 도출",
        "와이어프레임과 프로토타입 제작",
        "UX/UI 및 디자인 시스템 개선",
        "개발팀과 협업하여 디자인 품질과 일관성 보장",
      ],
      requirements: [
        "프로덕트 디자인 경력 5년 이상 또는 이에 준하는 역량",
        "Android, iOS, Web 실무 환경 이해",
        "디자인 시스템 기반 UI/UX 설계 경험",
        "논리적 설득력과 협업 능력",
      ],
      preferred: [
        "제품 설계부터 시장 출시까지 수행한 경험",
        "데이터 기반 제품 개선 경험",
        "패션, 방송, K-POP 플랫폼 디자인 경험",
        "우선순위와 마감 관리 능력",
      ],
    },
    qualification: {
      education: "",
      major: "",
      documents: ["포트폴리오 제출 필수"],
    },
    process: ["서류전형", "1·2차 면접", "평판조회", "채용검진", "처우협의", "합격자 발표"],
    workConditions: {
      employmentType: "정규직",
      workType: "상세 불명",
      salary: "",
      benefits: [],
      deadline: "2026-06-26",
      deadlineType: "fixed_date",
    },
  },
  {
    id: "500116c9eb165c7a8f97fbd3",
    companyName: "CJ ENM",
    title: "[Mnet Plus] Web/App Lead 경력채용",
    job: {
      name: "Mnet Plus Web/App Lead",
      headcount: "○명",
      locations: ["서울특별시 마포구 상암산로 66"],
      responsibilities: [
        "Web/App 프론트엔드 아키텍처와 기술 방향성 리딩",
        "라이브스트리밍, 투표, 결제 등 글로벌 핵심 기능 개발 주도",
        "안정적인 서비스 운영 체계 구축",
        "App 및 Web 개발 파트 매니징",
      ],
      requirements: [
        "프론트엔드 또는 모바일 테크 리드 경험 5년 이상",
        "개발 프로세스와 품질 기준을 설계하고 정착시킨 경험",
        "React Native 기반 서비스 개발 및 기술 리딩 경험",
        "JavaScript, TypeScript와 렌더링·성능·보안 이해",
        "다양한 직군과 협업 가능한 커뮤니케이션 역량",
      ],
      preferred: [
        "글로벌·다국어 서비스 개발 및 운영 경험",
        "초기 팀 빌딩과 개발 프로세스 구축 경험",
      ],
    },
    qualification: {
      education: "",
      major: "",
      documents: [],
    },
    process: ["2025.12.18부터 채용 시까지 상시채용"],
    workConditions: {
      employmentType: "정규직 (협의)",
      workType: "",
      salary: "회사 내규에 따름",
      benefits: [],
      deadline: null,
      deadlineType: "rolling",
    },
  },
  {
    id: "3ea3bda4afbc1216081bd4c1",
    companyName: "CJ ENM",
    title: "커머스부문 [개인정보보호 담당자] 경력사원 채용",
    job: {
      name: "개인정보보호 담당자",
      headcount: "",
      locations: ["서울"],
      responsibilities: [
        "개인정보보호 관리체계 운영 및 고도화",
        "개인정보보호 인증 관리",
        "임직원 정보보호 교육과 인식 제고",
        "개인정보 Life-Cycle 현황 점검 및 개선",
        "개인정보 관련 보안성 검토",
      ],
      requirements: [
        "개인정보보호 관리체계 구축 및 운영 경력 3~7년",
        "개인정보보호법 등 규제 영향도 분석 및 대응 경험",
        "규제기관 실태점검과 ISMS-P 인증 심사 대응 경험",
        "개인정보보호 관련 법률 이해",
        "다양한 조직과 협업하는 커뮤니케이션 역량",
      ],
      preferred: [
        "정보보호 관련 석사 학위",
        "ISMS-P 인증심사원",
        "Cloud 보안 관련 자격 또는 인증 관리 경험",
        "웹 및 오픈소스 개발 언어 활용 역량",
      ],
    },
    qualification: {
      education: "학사 이상",
      major: "전공 무관",
      documents: [],
    },
    process: ["서류전형", "면접전형"],
    workConditions: {
      employmentType: "정규직",
      workType: "",
      salary: "",
      benefits: [],
      deadline: "2026-06-14",
      deadlineType: "fixed_date",
    },
  },
]
